repos:
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: [
          --in-place,
          --remove-all-unused-imports,
          --remove-duplicate-keys,
          --ignore-init-module-imports,
          --ignore-pass-statements
        ]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: requirements-txt-fixer
        files: (requirements|constraints).*\.(in|txt)$
      - id: pretty-format-json
        args: ["--autofix", "--indent=2", "--no-ensure-ascii", "--no-sort-keys"]
      - id: trailing-whitespace
      - id: end-of-file-fixer
